/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_JniDemo */

#ifndef _Included_com_jnidemo_JniDemo
#define _Included_com_jnidemo_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_JniDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnidemo_JniDemo_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_jnidemo_JniDemo
 * Method:    setString
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnidemo_JniDemo_setString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
