/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_JniDemo */

#ifndef _Included_com_jnidemo_JniDemo
#define _Included_com_jnidemo_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_JniDemo
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnidemo_JniDemo_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
